package no.nav.bidrag.behandling.felles.enums

enum class VedtakType {
  MANUELT,
  AUTOMATISK_JUSTERING_BIDRAG,
  AUTOMATISK_REVURDERING_FORSKUDD,
  AUTOMATISK_REVURDERING_FORSKUDD_11_AAR,
  AUTOMATISK_INDEKSREGULERING,
  AUTOMATISK_OPPHØR_18_AAR,
  AUTOMATISK_ANNET
}